package com.tradeintel.config;

import com.tradeintel.entity.Stock;
import com.tradeintel.repository.StockRepository;
import com.tradeintel.repository.TradeSignalRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

/**
 * Seeds initial stock definitions ONLY. 
 * Real-time signals are generated by the TradeSignalEngine.
 */
@Component
@RequiredArgsConstructor
@Slf4j
public class DataInitializer implements CommandLineRunner {

    private final StockRepository stockRepository;
    private final TradeSignalRepository tradeSignalRepository;

    @Override
    public void run(String... args) {
        log.info("🚀 Data Initializer - Cleaning up stale data...");
        
        // Ensure Database is fresh on every restart to force Live data
        tradeSignalRepository.deleteAll();

        // 1. Ensure Baseline Stocks exist
        ensureStock("RELIANCE.NS", "Reliance Industries", "Energy");
        ensureStock("SBIN.NS", "State Bank of India", "Banking");
        ensureStock("BTC-USD", "Bitcoin", "Crypto");
        ensureStock("NIFTY 50", "Nifty 50 Index", "Indices");
        
        log.info("✅ Live Environment Ready. Waiting for Engine signals...");
    }

    private void ensureStock(String symbol, String name, String sector) {
        if (stockRepository.findBySymbol(symbol).isEmpty()) {
            stockRepository.save(Stock.builder()
                    .symbol(symbol)
                    .name(name)
                    .sector(sector)
                    .build());
        }
    }
}
